<?php
// database/seeders/AdminSeeder.php
namespace Database\Seeders;

use App\Models\Admin;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class AdminSeeder extends Seeder
{
    public function run(): void
    {
        $admins = [
            [
                'first_name' => 'John',
                'last_name' => 'Smith',
                'phone' => '+1234567890',
                'address' => '123 Main St, New York, NY 10001',
                'email' => 'super.admin@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'admin_status' => 'super_admin',
                'is_active' => true,
                'staff_role' => 'Operations Manager',
                'other_role' => null,
                'date_of_birth' => '1985-03-15',
                'photo' => 'admin_photos/john_smith.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Sarah',
                'last_name' => 'Johnson',
                'phone' => '+1234567891',
                'address' => '456 Oak Ave, Los Angeles, CA 90001',
                'email' => 'sarah.johnson@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'admin_status' => 'manager',
                'is_active' => true,
                'staff_role' => 'HR',
                'other_role' => null,
                'date_of_birth' => '1990-07-22',
                'photo' => 'admin_photos/sarah_johnson.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Michael',
                'last_name' => 'Chen',
                'phone' => '+1234567892',
                'address' => '789 Pine St, Chicago, IL 60601',
                'email' => 'michael.chen@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'admin_status' => 'manager',
                'is_active' => true,
                'staff_role' => 'IT',
                'other_role' => null,
                'date_of_birth' => '1988-11-30',
                'photo' => 'admin_photos/michael_chen.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Emily',
                'last_name' => 'Rodriguez',
                'phone' => '+1234567893',
                'address' => '321 Elm Blvd, Houston, TX 77001',
                'email' => 'emily.rodriguez@example.com',
                'password' => Hash::make('password123'),
                'admin_status' => 'staff',
                'is_active' => true,
                'staff_role' => 'Designer',
                'other_role' => null,
                'date_of_birth' => '1992-04-18',
                'photo' => 'admin_photos/emily_rodriguez.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'David',
                'last_name' => 'Kim',
                'phone' => '+1234567894',
                'address' => '654 Cedar Ln, Miami, FL 33101',
                'email' => 'david.kim@example.com',
                'password' => Hash::make('password123'),
                'admin_status' => 'staff',
                'is_active' => false,
                'staff_role' => 'Operator',
                'other_role' => null,
                'date_of_birth' => '1995-09-05',
                'photo' => 'admin_photos/david_kim.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Lisa',
                'last_name' => 'Thompson',
                'phone' => '+1234567895',
                'address' => '987 Birch Rd, Seattle, WA 98101',
                'email' => 'lisa.thompson@example.com',
                'password' => Hash::make('password123'),
                'admin_status' => 'staff',
                'is_active' => true,
                'staff_role' => 'customer_service',
                'other_role' => null,
                'date_of_birth' => '1991-12-12',
                'photo' => 'admin_photos/lisa_thompson.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'James',
                'last_name' => 'Wilson',
                'phone' => '+1234567896',
                'address' => '147 Spruce Dr, Denver, CO 80201',
                'email' => 'james.wilson@example.com',
                'password' => Hash::make('password123'),
                'admin_status' => 'staff',
                'is_active' => true,
                'staff_role' => 'QC',
                'other_role' => null,
                'date_of_birth' => '1987-08-25',
                'photo' => 'admin_photos/james_wilson.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Maria',
                'last_name' => 'Garcia',
                'phone' => '+1234567897',
                'address' => '258 Willow Way, Phoenix, AZ 85001',
                'email' => 'maria.garcia@example.com',
                'password' => Hash::make('password123'),
                'admin_status' => 'staff',
                'is_active' => true,
                'staff_role' => 'Finance',
                'other_role' => null,
                'date_of_birth' => '1989-06-03',
                'photo' => 'admin_photos/maria_garcia.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Robert',
                'last_name' => 'Taylor',
                'phone' => '+1234567898',
                'address' => '369 Maple Ave, Boston, MA 02101',
                'email' => 'robert.taylor@example.com',
                'password' => Hash::make('password123'),
                'admin_status' => 'staff',
                'is_active' => false,
                'staff_role' => 'other',
                'other_role' => 'Maintenance',
                'date_of_birth' => '1986-02-14',
                'photo' => 'admin_photos/robert_taylor.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($admins as $admin) {
            Admin::create($admin);
        }
    }
}