<?php

// config/mail.php
// Add 'hr_email' to the existing mail config array.
// The full file is generated by Laravel — just add this one key.

return [

    'default' => env('MAIL_MAILER', 'smtp'),

    'mailers' => [
        'smtp' => [
            'transport'  => 'smtp',
            'host'       => env('MAIL_HOST', 'smtp.mailgun.org'),
            'port'       => env('MAIL_PORT', 587),
            'encryption' => env('MAIL_ENCRYPTION', 'tls'),
            'username'   => env('MAIL_USERNAME'),
            'password'   => env('MAIL_PASSWORD'),
            'timeout'    => null,
        ],
        // ...other mailers
    ],

    'from' => [
        'address' => env('MAIL_FROM_ADDRESS', 'noreply@printbuka.com'),
        'name'    => env('MAIL_FROM_NAME', 'Printbuka HR'),
    ],

    // ─── ADD THIS ───────────────────────────────────────────────────────────
    'hr_email' => env('HR_EMAIL', 'hr@printbuka.com'),
    // ────────────────────────────────────────────────────────────────────────

];
